[workspace]
resolver = "2"
members = [
    "crates/lithe",
    "crates/lithe-core",
    "crates/lithe-macros",
    "crates/lithe-cli",
    "crates/lithe-ui",
    "examples/static-starter",
    "examples/project",
    "examples/my-app",
]
